### ISSUE TITLE
Add support for elasticsearch 5.0

### ISSUE THREAD

**Issue by dadoonet** [dadoonet/fscrawler#166]
The mapping used for elasticsearch 5.0 changed.

As proposed by @sgoeschl in https://github.com/dadoonet/fscrawler/issues/153#issuecomment-221668892, we should try to have multiple mapping files definition.
It could be nice indeed to put those files as resources instead of building them in Java and have mappings per major elasticsearch version.

As also proposed in https://github.com/dadoonet/fscrawler/issues/153#issuecomment-221671165, would be super nice to let the user easily defined his own template per job.

This issue is meant to track all those changes:

- [x] #167: Get mappings from resource files instead of Java based mappings. 
- [x] #173: Add support for multiple mapping templates depending on elasticsearch version 
- [x] #168: Copy automatically at startup resource files to fscrawler config directory (add in the README that people who want to overwrite existing files with new mapping template should remove the mapping templates in config dir and restart)
- [x] #169: Let the user specify its own mapping file per job
- [x] #175: Split tests into unit tests and real integration tests
- [x] #171: Update to 5.0

Note that this version ready for 5.0 should work against 2.x and 5.x series (potentially previous versions like 1.x).
